<a href="https://colab.research.google.com/github/obeabi/DeepLearning/blob/master/BankChurn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Written by Abiola Obembe
## Title : Bank Churn
### Date : 2020-09-04
### Objective: Neural network model for predicting customer churn

In [29]:
# install libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import seaborn as sns
%matplotlib inline

print("libraies installed successfully!")

libraies installed successfully!


In [30]:
# print tensorflow version
print(" The tensorflow version is"   ,    str(tf.__version__))

 The tensorflow version is 2.3.0


## Step 1: Data Pre-Processing

### Import dataset

In [31]:
# import dataset
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

### Data Cleaning

In [32]:
# Split dataset into dependent and independent varaibles
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X.shape)
print(y.shape)

(10000, 10)
(10000,)


In [55]:
# Exploratotory analysis for Gender column
dataset['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [56]:
# Exploratotory analysis for Geography column
dataset['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [33]:
# check for missing values
missing_values = dataset.isnull().sum()
print(missing_values)
print("The total number of missing values is", missing_values.sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
The total number of missing values is 0


In [34]:
# print X
print(X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [35]:
# print y
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical variables

In [36]:
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [37]:
# Print shape of X
print(X.shape)
print(X[:, :6])

(10000, 13)
[[1.0 0.0 0.0 1.0 0.0 619]
 [0.0 0.0 1.0 1.0 0.0 608]
 [1.0 0.0 0.0 1.0 0.0 502]
 ...
 [1.0 0.0 0.0 1.0 0.0 709]
 [0.0 1.0 0.0 0.0 1.0 772]
 [1.0 0.0 0.0 1.0 0.0 792]]


### Split dataset into Training and Testing set

In [38]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 13)
(2000, 13)
(8000,)
(2000,)


### Feature Scaling

In [39]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]


## Step 2: Build the ANN

### Initialze ANN

In [46]:
# Initialize ANN network
ann = tf.keras.models.Sequential()
ann

### Add input and first hidden layer

In [47]:
# Establish the first hidden layer of the NN
n_H1 = 6
ann.add(tf.keras.layers.Dense( units= n_H1, activation= 'relu'))

### Add second hidden layer

In [48]:
# Establish the second hidden layer of the NN
n_H2 = 3
ann.add(tf.keras.layers.Dense( units= n_H2, activation= 'relu'))

### Add the output layer

In [49]:
# Establish output layer
ann.add(tf.keras.layers.Dense( units= 1, activation= 'sigmoid')) # softmax

## Step 3: Train the ANN

### Compile the ANN

In [50]:
# comile NN
ann.compile(optimizer= 'adam', loss = 'binary_crossentropy' , metrics= ['accuracy'] ) # sgd,rmsprop,nadam,ftrl,adamax,adagrad, categorical_crossentropy


### Train on Training set

In [51]:
# Train NN
ann.fit(x= X_train, y = y_train, batch_size= 2**5, epochs = 200)

Epoch 1/200
250/250 [==============================] - 0s 1ms/step - loss: 0.7297 - accuracy: 0.6003
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4998 - accuracy: 0.7918
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4526 - accuracy: 0.7985
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4405 - accuracy: 0.8026
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4316 - accuracy: 0.8095
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4233 - accuracy: 0.8169
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4157 - accuracy: 0.8240
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4094 - accuracy: 0.8284
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4038 - accuracy: 0.8313
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3980 - accura

## Step 4: Prediction from NN

### Make prediction from NN

In [67]:
# Make prediction for single customer with the following details
# Geography : France
# Credit Score :600
# Gender: Male
# Age : 40 years
# Tenure : 3 years
# Balance : $60,000
#  Number of Products : 2
# Does this customer have a credit card? : Yes
#  Is this Customer an active member?: Yes
# Estimated salary: $ 50,000
# Churn?: Yes (1) or No (0)

X_new = [[1.0, 0.0, 0.0, 1.0, 0.0,600,40,3,60000,2,1,1,50000    ]]
X_new_sc = sc.transform(X_new)
print(ann.predict(X_new_sc) > 0.5)



[[False]]


### Prediction and evaluation from test set

In [68]:
# Predicting the Test set results
y_thresh = 0.5
y_pred = ann.predict(X_test)
y_pred = (y_pred > y_thresh)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


In [69]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   60]
 [ 226  189]]


0.857